### ISSUE TITLE
I remember you!

### ISSUE THREAD

**Issue by Explosion-Scratch** [ego-lay-atman-bay/ego-lay-atman-bay#1]
Didn't you help with that Terraria save codes thread?

**Comment by ego-lay-atman-bay** [comment]
Yeah, at least I think I know what you're talking about.

**Comment by Explosion-Scratch** [comment]
https://scratch.mit.edu/discuss/topic/373997/?page=1

Oh yeah =)

**Comment by ego-lay-atman-bay** [comment]
I knew I remembered you
